### ISSUE TITLE
i386 architecture input is incompatiable with i389:x86_64 output

### ISSUE THREAD

**Issue by Humni** [ROBOTIS-OP/robotis_op_framework#1]
When I am running catkin_make in my environment which has this framework I am getting this error. After getting rid of a previous error from the robotis_op_camera by placing (copying) the Finddarwin_lib.cmake in the /usr/share/cmake-2.8/Modules directory I am now getting the following error when I run catkin_make:

```
Linking CXX shared library /home/humni/ros-darwin/devel/lib/librobotis_op_camera.so
/usr/bin/ld: i386 architecture of input file `/home/humni/ros-darwin/src/robotis_op_framework/Linux/lib/darwin.a(LinuxCamera.o)' is incompatible with i386:x86-64 output
...
...
Image.cpp:(.text+0x254): undefined reference to `operator new[](unsigned int)'
Image.cpp:(.text+0x26a): undefined reference to `operator new(unsigned int)'
Image.cpp:(.text+0x298): undefined reference to `operator new[](unsigned int)'
/home/humni/ros-darwin/src/robotis_op_framework/Linux/lib/darwin.a(ImgProcess.o): In function `Robot::ImgProcess::Erosion(Robot::Image*)':
ImgProcess.cpp:(.text+0x31c): undefined reference to `operator new[](unsigned int)'
/home/humni/ros-darwin/src/robotis_op_framework/Linux/lib/darwin.a(ImgProcess.o): In function `Robot::ImgProcess::Dilation(Robot::Image*)':
ImgProcess.cpp:(.text+0x58c): undefined reference to `operator new[](unsigned int)'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/humni/ros-darwin/devel/lib/librobotis_op_camera.so] Error 1
make[1]: *** [robotis_op_camera/CMakeFiles/robotis_op_camera.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j8 -l8" failed
```

**Comment by kdaun** [comment]
Hi,

the error message indicates a mismatch between the darwin_lib which is compiled for a 32bit OS and your 64bit OS.

Did you try to build it on your OP2 or your computer? Which operating system are you using (32/64bit)?

The robotis_op_camera package depends on the darwin_lib which runs on the robot and requires a 32bit OS. If you want to simulate the robot on your computer (e.g. with Gazebo)  this package is not needed.

Further information about installion can be found here: [Installation on computer](https://github.com/ROBOTIS-OP/robotis_op_documentation/wiki/Installation-on--PC) and [Installation on robot](https://github.com/ROBOTIS-OP/robotis_op_documentation/wiki/Installation-on-ROBOTIS-OP2)

**Comment by Humni** [comment]
Thanks for the reply. You pointed me in the right direction and have got everything working now. I am not sure if I followed the tutorials wrong or there is some name changes but I have not been able to get the walking simulation working now. Different issue however so if I can't get it working I will open another issue elsewhere. Thanks for your help
