### ISSUE TITLE
joint_states effort message

### ISSUE THREAD

**Issue by bendata61** [ROBOTIS-OP/robotis_op_framework#2]
Hi,
Currently ROS /robotis_op/joint_state msgs have effort as nan. Is it possible for the torque efforts being published as well? Else, is there a method to access this info from the dynamixels directly.

**Comment by kdaun** [comment]
Hi,
unfortunately the MX-28 actuators don't provide torque information, thus it's not possible to publish the torque.
For more information about the features of the MX-28 actuators check the [ROBOTIS e-manual](http://support.robotis.com/en/product/dynamixel/mx_series/mx-28.htm) and the [product page](http://www.robotis.us/mx-series/).

**Comment by bendata61** [comment]
Hi,
If the mx-28 can't provide torque info, would it be possible to get the current draw for each motor? since the torque can be calculated roughly from it.

**Comment by kdaun** [comment]
Unfortunately, the MX-28 does not provide any electrical current information. From the MX series, only MX-64 and MX-106 provide the current draw.

**Comment by bendata61** [comment]
Thanks for all your help. It's unfortunate this information is not provided.
